version: "3.8"
services:
  doc_generator:
    build: .
    restart: always
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./src/temp:/app/src/temp
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
